# Generated by Django 4.2.1 on 2023-05-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
                ('location', models.URLField()),
                ('resource_type', models.CharField(choices=[('B', 'Book'), ('V', 'Video')], max_length=1)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('video_duration', models.DurationField(blank=True, null=True)),
                ('progress_pages', models.IntegerField(blank=True, null=True)),
                ('progress_time', models.DurationField(blank=True, null=True)),
                ('progress_percent', models.FloatField(blank=True, null=True)),
                ('topics', models.ManyToManyField(to='learn.topic')),
            ],
        ),
    ]
